spring:
  application:
    name: pricingengine
  datasource:
    url: jdbc:postgresql://originationdb.cqn0ge686n65.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: local1234
    driver-class-name: org.postgresql.Driver
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html